name: essence
description: A starting point for Dart libraries or applications.
version: 0.0.1
repository: https://www.github.com/bradcypert/essence
# homepage: https://www.example.com

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  html: ^0.14.0+3
  universal_html: ^1.2.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
