name: essence
description: A super simple virtual DOM implementation in Dart. Supports Diffing, too!
version: 0.0.1+4
repository: https://www.github.com/bradcypert/essence

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  html: ^0.14.0+3
  universal_html: ^1.2.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
